'use client'
import './shared.jsx'
export { PgDashboard } from './pages/PgDashboard.jsx'
export { PgSchedule } from './pages/PgSchedule.jsx'
export { PgClasses } from './pages/PgClasses.jsx'
export { PgModules } from './pages/PgModules.jsx'
export { PgSyllabus } from './pages/PgSyllabus.jsx'
export { PgScholar } from './pages/PgScholar.jsx'
export { PgMaterials } from './pages/PgMaterials.jsx'
export { PgStudents } from './pages/PgStudents.jsx'
export { PgResearch } from './pages/PgResearch.jsx'
export { PgSupervision } from './pages/PgSupervision.jsx'
export { PgInternship } from './pages/PgInternship.jsx'
export { PgTools } from './pages/PgTools.jsx'
export { PgGrades } from './pages/PgGrades.jsx'
export { PgAdmin } from './pages/PgAdmin.jsx'
export { PgFinance } from './pages/PgFinance.jsx'
export { PgProfile } from './pages/PgProfile.jsx'
export { PgNotifications } from './pages/PgNotifications.jsx'
export { PgTickets } from './pages/PgTickets.jsx'
export { PgSettings } from './pages/PgSettings.jsx'
