'use client'
import './shared.jsx'
export { LifeHubPage } from './pages/LifeHubPage.jsx'
export { CampusPage } from './pages/CampusPage.jsx'
export { ActivitiesPage } from './pages/ActivitiesPage.jsx'
export { ActivityDetailPage } from './pages/ActivityDetailPage.jsx'
export { ClubListPage } from './pages/ClubListPage.jsx'
export { ClubDetailPage } from './pages/ClubDetailPage.jsx'
export { YouthUnionPage } from './pages/YouthUnionPage.jsx'
export { SportsCulturePage } from './pages/SportsCulturePage.jsx'
export { DormPage } from './pages/DormPage.jsx'
export { HealthPage } from './pages/HealthPage.jsx'
export { CampusServicesPage } from './pages/CampusServicesPage.jsx'
export { StudentSupportPage } from './pages/StudentSupportPage.jsx'
export { JobsPage } from './pages/JobsPage.jsx'
export { JobDetailPage } from './pages/JobDetailPage.jsx'
