'use client'
import './shared.jsx'
export { StaffGatewayPage } from './pages/StaffGatewayPage.jsx'
export { StfTeachingPage } from './pages/StfTeachingPage.jsx'
export { StfResearchPage } from './pages/StfResearchPage.jsx'
export { StfRegulationsPage } from './pages/StfRegulationsPage.jsx'
export { StfFormsPage } from './pages/StfFormsPage.jsx'
export { StaffDirectoryPage } from './pages/StaffDirectoryPage.jsx'
export { StfUtilitiesPage } from './pages/StfUtilitiesPage.jsx'
export { StfPortalPage } from './pages/StfPortalPage.jsx'
