'use client'
import './shared.jsx'
export { NewsListPage } from './pages/NewsListPage.jsx'
export { NewsDetailPage } from './pages/NewsDetailPage.jsx'
export { EventListPage } from './pages/EventListPage.jsx'
export { EventDetailPage } from './pages/EventDetailPage.jsx'
export { MediaPage } from './pages/MediaPage.jsx'
export { AlbumDetailPage } from './pages/AlbumDetailPage.jsx'
export { VideoDetailPage } from './pages/VideoDetailPage.jsx'
export { PodcastDetailPage } from './pages/PodcastDetailPage.jsx'
export { SearchResultsPage } from './pages/SearchResultsPage.jsx'
