'use client'
import './shared.jsx'
export { OverviewPage } from './pages/OverviewPage.jsx'
export { RectorMessagePage } from './pages/RectorMessagePage.jsx'
export { HistoryPage } from './pages/HistoryPage.jsx'
export { VisionPage } from './pages/VisionPage.jsx'
export { AchievementsPage } from './pages/AchievementsPage.jsx'
export { NumbersPage } from './pages/NumbersPage.jsx'
export { OrgChartPage } from './pages/OrgChartPage.jsx'
export { BoardPage } from './pages/BoardPage.jsx'
export { UnitListPage } from './pages/UnitListPage.jsx'
export { UnitDetailPage } from './pages/UnitDetailPage.jsx'
export { DepartmentDetailPage } from './pages/DepartmentDetailPage.jsx'
export { LecturerDetailPage } from './pages/LecturerDetailPage.jsx'
export { FacultyStaffPage } from './pages/FacultyStaffPage.jsx'
