'use client'
import './shared.jsx'
export { PpDashboard } from './pages/PpDashboard.jsx'
export { PpChild } from './pages/PpChild.jsx'
export { PpResults } from './pages/PpResults.jsx'
export { PpTuition } from './pages/PpTuition.jsx'
export { PpAttendance } from './pages/PpAttendance.jsx'
export { PpNotices } from './pages/PpNotices.jsx'
export { PpContact } from './pages/PpContact.jsx'
export { PpServices } from './pages/PpServices.jsx'
export { PpSchedule } from './pages/PpSchedule.jsx'
export { PpSettings } from './pages/PpSettings.jsx'
