'use client'
import './shared.jsx'
export { StudentGatewayPage } from './pages/StudentGatewayPage.jsx'
export { StuLearningPage } from './pages/StuLearningPage.jsx'
export { StuRegulationsPage } from './pages/StuRegulationsPage.jsx'
export { StuTuitionPage } from './pages/StuTuitionPage.jsx'
export { StuFormsPage } from './pages/StuFormsPage.jsx'
export { StuLifePage } from './pages/StuLifePage.jsx'
export { StuJobsPage } from './pages/StuJobsPage.jsx'
export { StuLibraryPage } from './pages/StuLibraryPage.jsx'
export { StuPortalPage } from './pages/StuPortalPage.jsx'
export { StuOnboardingPage } from './pages/StuOnboardingPage.jsx'
export { StuFaqPage } from './pages/StuFaqPage.jsx'
