export const cmsConfig = {
  key: 'cms',
  base: '/cms',
  role: 'Super Admin',
  user: 'Trần Văn Minh',
  meta: 'Super Admin · Ban Truyền thông',
  wireframe: 'PG-PORT-CMS · CMS-01 → CMS-10',
  notifTo: '/cms/nhat-ky',
  notifications: [
    { title: '3 bài viết đang chờ duyệt', time: 'Hôm nay 10:15', unread: true },
    { title: 'Lê Thị Mai vừa tải lên banner-tuyensinh.jpg', time: '16/05/2025 09:30', unread: true },
    { title: 'Sao lưu hệ thống hoàn tất (425.6 MB)', time: '16/05/2025 03:00', unread: false },
  ],
  items: [
    { path: '', title: 'Tổng quan', icon: 'grid', wireframe: 'CMS-01' },
    { path: 'bai-viet', title: 'Bài viết', icon: 'newspaper', wireframe: 'CMS-02' },
    { path: 'bai-viet/moi', title: 'Thêm / Chỉnh sửa bài viết', icon: 'file', wireframe: 'CMS-03', hidden: true },
    { path: 'bai-viet/moi/:id', title: 'Chỉnh sửa bài viết', icon: 'file', wireframe: 'CMS-03', hidden: true },
    { path: 'danh-muc', title: 'Danh mục', icon: 'layers', wireframe: 'CMS-04' },
    { path: 'media', title: 'Media thư viện', icon: 'image', wireframe: 'CMS-05' },
    { path: 'trang-menu', title: 'Trang & Menu', icon: 'menu', wireframe: 'CMS-06' },
    { path: 'su-kien', title: 'Sự kiện', icon: 'calendar', wireframe: 'CMS-02' },
    { path: 'tuyen-sinh', title: 'Tuyển sinh', icon: 'compass', wireframe: 'CMS-02' },
    { path: 'nghien-cuu', title: 'Nghiên cứu', icon: 'flask', wireframe: 'CMS-02' },
    { path: 'hoc-tap', title: 'Học tập', icon: 'book', wireframe: 'CMS-02' },
    { path: 'banner', title: 'Banner / Slider', icon: 'image', wireframe: 'CMS-02' },
    { path: 'trang-chu', title: 'Trang chủ', icon: 'home', wireframe: 'CMS-02' },
    { path: 'album', title: 'Album ảnh', icon: 'image', wireframe: 'CMS-02' },
    { path: 'video', title: 'Video', icon: 'play', wireframe: 'CMS-02' },
    { path: 'podcast', title: 'Podcast', icon: 'headphones', wireframe: 'CMS-02' },
    { path: 'nguoi-dung', title: 'Người dùng', icon: 'users', wireframe: 'CMS-07' },
    { path: 'phan-quyen', title: 'Vai trò & Phân quyền', icon: 'shield', wireframe: 'CMS-07' },
    { path: 'cau-hinh', title: 'Cấu hình hệ thống', icon: 'lock', wireframe: 'CMS-08' },
    { path: 'nhat-ky', title: 'Nhật ký hoạt động', icon: 'clock', wireframe: 'CMS-09' },
    { path: 'sao-luu', title: 'Sao lưu & Phục hồi', icon: 'download', wireframe: 'CMS-10' },
  ],
}
