export const cmsConfig = {
  key: 'cms',
  base: '/cms',
  role: 'Super Admin',
  user: 'Trần Văn Minh',
  meta: 'Super Admin · Ban Truyền thông',
  wireframe: 'PG-PORT-CMS · CMS-01 → CMS-10',
  notifTo: '/cms/nhat-ky',
  notifications: [
    { title: '3 bài viết đang chờ duyệt', time: 'Hôm nay 10:15', unread: true },
    { title: 'Lê Thị Mai vừa tải lên banner-tuyensinh.jpg', time: '16/05/2025 09:30', unread: true },
    { title: 'Sao lưu hệ thống hoàn tất (425.6 MB)', time: '16/05/2025 03:00', unread: false },
  ],
  items: [
    { path: '', title: 'Tổng quan', icon: 'grid', wireframe: 'CMS-01' },
    { path: 'bai-viet', title: 'Bài viết', icon: 'newspaper', wireframe: 'CMS-02', group: 'Nội dung' },
    { path: 'bai-viet/moi', title: 'Thêm / Chỉnh sửa bài viết', icon: 'file', wireframe: 'CMS-03', hidden: true },
    { path: 'bai-viet/moi/:id', title: 'Chỉnh sửa bài viết', icon: 'file', wireframe: 'CMS-03', hidden: true },
    { path: 'thong-bao', title: 'Thông báo', icon: 'bell', wireframe: 'CMS-ANN', group: 'Nội dung' },
    { path: 'thong-bao/moi', title: 'Soạn thông báo', icon: 'bell', hidden: true },
    { path: 'thong-bao/moi/:id', title: 'Chỉnh sửa thông báo', icon: 'bell', hidden: true },
    { path: 'danh-muc', title: 'Danh mục', icon: 'layers', wireframe: 'CMS-04', group: 'Nội dung' },
    { path: 'media', title: 'Media thư viện', icon: 'upload', wireframe: 'CMS-05', group: 'Nội dung' },
    /* Lối tắt: danh sách bài viết đã lọc sẵn theo chuyên mục */
    { path: 'su-kien', title: 'Sự kiện', icon: 'calendar', wireframe: 'CMS-02', group: 'Bài viết theo chuyên mục' },
    { path: 'tuyen-sinh', title: 'Tuyển sinh', icon: 'compass', wireframe: 'CMS-02', group: 'Bài viết theo chuyên mục' },
    { path: 'nghien-cuu', title: 'Nghiên cứu', icon: 'flask', wireframe: 'CMS-02', group: 'Bài viết theo chuyên mục' },
    { path: 'hoc-tap', title: 'Học tập', icon: 'book', wireframe: 'CMS-02', group: 'Bài viết theo chuyên mục' },
    { path: 'trang-chu', title: 'Trang chủ', icon: 'home', wireframe: 'CMS-02', group: 'Website' },
    { path: 'banner', title: 'Banner / Slider', icon: 'target', wireframe: 'CMS-02', group: 'Website' },
    { path: 'trang-menu', title: 'Trang & Menu', icon: 'menu', wireframe: 'CMS-06', group: 'Website' },
    { path: 'album', title: 'Album ảnh', icon: 'image', wireframe: 'CMS-02', group: 'Website' },
    { path: 'video', title: 'Video', icon: 'play', wireframe: 'CMS-02', group: 'Website' },
    { path: 'podcast', title: 'Podcast', icon: 'headphones', wireframe: 'CMS-02', group: 'Website' },
    /* Người dùng & vai trò quản lý trên SSO; CMS chỉ phân quyền mức bản ghi */
    { path: 'trang-don-vi', title: 'Trang đơn vị', icon: 'building', wireframe: 'CMS-11', requires: 'tenant.manage', group: 'Quản trị' },
    { path: 'phan-quyen', title: 'Phân quyền nội dung', icon: 'shield', wireframe: 'CMS-07', requires: 'grant.manage', group: 'Quản trị' },
    { path: 'cau-hinh', title: 'Cấu hình hệ thống', icon: 'settings', wireframe: 'CMS-08', requires: 'settings.manage', group: 'Quản trị' },
    { path: 'nhat-ky', title: 'Nhật ký hoạt động', icon: 'clock', wireframe: 'CMS-09', requires: 'log.view', group: 'Quản trị' },
    { path: 'sao-luu', title: 'Sao lưu & Phục hồi', icon: 'download', wireframe: 'CMS-10', requires: 'backup.manage', group: 'Quản trị' },
  ],
}
