'use client'
import './shared.jsx'
export { EducationHubPage } from './pages/EducationHubPage.jsx'
export { ProgramListPage } from './pages/ProgramListPage.jsx'
export { ProgramDetailPage } from './pages/ProgramDetailPage.jsx'
export { LearningOutcomesPage } from './pages/LearningOutcomesPage.jsx'
export { GeneralInfoPage } from './pages/GeneralInfoPage.jsx'
export { TuitionScholarshipPage } from './pages/TuitionScholarshipPage.jsx'
export { AcademicCalendarPage } from './pages/AcademicCalendarPage.jsx'
export { ResultLookupPage } from './pages/ResultLookupPage.jsx'
export { StudyGuidesPage } from './pages/StudyGuidesPage.jsx'
export { SurveyPage } from './pages/SurveyPage.jsx'
