'use client'
import './shared.jsx'
export { UtilitiesHubPage } from './pages/UtilitiesHubPage.jsx'
export { ELearningPage } from './pages/ELearningPage.jsx'
export { DigitalLibraryPage } from './pages/DigitalLibraryPage.jsx'
export { FormsPage } from './pages/FormsPage.jsx'
export { WorkCalendarPage } from './pages/WorkCalendarPage.jsx'
export { WebmailPage } from './pages/WebmailPage.jsx'
export { ContactPage } from './pages/ContactPage.jsx'
