'use client'
import './shared.jsx'
export { CmsDashboard } from './pages/CmsDashboard.jsx'
export { CmsPosts } from './pages/CmsPosts.jsx'
export { CmsEvents } from './pages/CmsEvents.jsx'
export { CmsAdmissions } from './pages/CmsAdmissions.jsx'
export { CmsResearch } from './pages/CmsResearch.jsx'
export { CmsLearning } from './pages/CmsLearning.jsx'
export { CmsPostEditor } from './pages/CmsPostEditor.jsx'
export { CmsCategories } from './pages/CmsCategories.jsx'
export { CmsMedia } from './pages/CmsMedia.jsx'
export { CmsPagesMenu } from './pages/CmsPagesMenu.jsx'
export { CmsGrants } from './pages/CmsGrants.jsx'
export { CmsAnnouncements } from './pages/CmsAnnouncements.jsx'
export { CmsAnnouncementEditor } from './pages/CmsAnnouncementEditor.jsx'
export { CmsSettings } from './pages/CmsSettings.jsx'
export { CmsActivity } from './pages/CmsActivity.jsx'
export { CmsBackup } from './pages/CmsBackup.jsx'
export { CmsBanners } from './pages/CmsBanners.jsx'
export { CmsAlbums } from './pages/CmsAlbums.jsx'
export { CmsVideos } from './pages/CmsVideos.jsx'
export { CmsPodcasts } from './pages/CmsPodcasts.jsx'
export { CmsHome } from './pages/CmsHome.jsx'
