'use client'
import './shared.jsx'
export { PsDashboard } from './pages/PsDashboard.jsx'
export { PsStudyCorner } from './pages/PsStudyCorner.jsx'
export { PsResults } from './pages/PsResults.jsx'
export { PsSchedule } from './pages/PsSchedule.jsx'
export { PsTuition } from './pages/PsTuition.jsx'
export { PsForms } from './pages/PsForms.jsx'
export { PsProgress } from './pages/PsProgress.jsx'
export { PsProfile } from './pages/PsProfile.jsx'
export { PsNotifications } from './pages/PsNotifications.jsx'
export { PsTickets } from './pages/PsTickets.jsx'
export { PsSettings } from './pages/PsSettings.jsx'
export { PsServices } from './pages/PsServices.jsx'
export { PsLibrary } from './pages/PsLibrary.jsx'
export { PsRegCourses } from './pages/PsRegCourses.jsx'
export { PsRegThesis } from './pages/PsRegThesis.jsx'
export { PsRegIntern } from './pages/PsRegIntern.jsx'
