'use client'
import './shared.jsx'
export { PlDashboard } from './pages/PlDashboard.jsx'
export { PlBI } from './pages/PlBI.jsx'
export { PlReports } from './pages/PlReports.jsx'
export { PlApprovals } from './pages/PlApprovals.jsx'
export { PlSystem } from './pages/PlSystem.jsx'
export { PlPortalSettings } from './pages/PlPortalSettings.jsx'
export { PlSysLog } from './pages/PlSysLog.jsx'
export { PlNotifications } from './pages/PlNotifications.jsx'
export { PlDomain } from './pages/PlDomain.jsx'
export { PlTraining } from './pages/PlTraining.jsx'
export { PlResearch } from './pages/PlResearch.jsx'
export { PlStudents } from './pages/PlStudents.jsx'
export { PlFinance } from './pages/PlFinance.jsx'
export { PlHR } from './pages/PlHR.jsx'
export { PlFacilities } from './pages/PlFacilities.jsx'
