'use client'
import './shared.jsx'
export { AdmissionsHubPage } from './pages/AdmissionsHubPage.jsx'
export { AdmInfoPage } from './pages/AdmInfoPage.jsx'
export { AdmMethodsPage } from './pages/AdmMethodsPage.jsx'
export { AdmDossierPage } from './pages/AdmDossierPage.jsx'
export { AdmTimelinePage } from './pages/AdmTimelinePage.jsx'
export { AdmGuidePage } from './pages/AdmGuidePage.jsx'
export { AdmBenchmarkPage } from './pages/AdmBenchmarkPage.jsx'
export { AdmRegulationsPage } from './pages/AdmRegulationsPage.jsx'
export { AdmVideosPage } from './pages/AdmVideosPage.jsx'
export { AdmAdvisoryPage } from './pages/AdmAdvisoryPage.jsx'
export { AdmFaqPage } from './pages/AdmFaqPage.jsx'
