'use client'
import './shared.jsx'
export { ResearchHubPage } from './pages/ResearchHubPage.jsx'
export { ProjectListPage } from './pages/ProjectListPage.jsx'
export { ProjectDetailPage } from './pages/ProjectDetailPage.jsx'
export { PublicationListPage } from './pages/PublicationListPage.jsx'
export { PublicationDetailPage } from './pages/PublicationDetailPage.jsx'
export { ExpertListPage } from './pages/ExpertListPage.jsx'
export { ResearchGroupsPage } from './pages/ResearchGroupsPage.jsx'
export { ConferencesPage } from './pages/ConferencesPage.jsx'
export { LabsPage } from './pages/LabsPage.jsx'
export { TechTransferPage } from './pages/TechTransferPage.jsx'
export { PhdTrainingPage } from './pages/PhdTrainingPage.jsx'
export { ExpertDetailPage } from './pages/ExpertDetailPage.jsx'
export { ResearchGroupDetailPage } from './pages/ResearchGroupDetailPage.jsx'
export { ConferenceDetailPage } from './pages/ConferenceDetailPage.jsx'
export { LabDetailPage } from './pages/LabDetailPage.jsx'
